// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiqyaeoekafkuwqfzzvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcXlhZW9la2Fma3V3cWZ6enZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjA5NDEsImV4cCI6MjA3MzQ5Njk0MX0.yxVodW4F7VLHD9Ovzo0KsMx8BjNFLf2b8Ky3_R4Mj8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});